name: Test CI Build Manually

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름 (예: user, product, gateway 등)'
        required: true
        default: 'gateway'
      sha:
        description: '이미지 태그용 SHA (생략 시 자동 생성)'
        required: false

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev repo
        uses: actions/checkout@v3
        with:
          repository: WellPT-Profect-2th/dev
          token: ${{ secrets.DEV_REPO_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load .env
        run: |
          echo "${{ secrets.TEST_ENV_FILE }}" > .env
          set -a
          source .env
          set +a

      # - name: Set tag name
      #   id: set-tag
      #   run: |
      #     if [ -z "${{ github.event.inputs.sha }}" ]; then
      #       TAG=$(git rev-parse --short HEAD)
      #     else
      #       TAG="${{ github.event.inputs.sha }}"
      #     fi
      #     echo "tag=$TAG" >> $GITHUB_OUTPUT

      # - name: Run tests / build
      #   run: |
      #     SERVICE="${{ github.event.inputs.service }}"
      #     if [ "$SERVICE" == "frontend" ]; then
      #       cd frontend
      #       npm install
      #       npm run build
      #     else
      #       cd backend/$SERVICE
      #       if [ -f "gradlew" ]; then
      #         ./gradlew test
      #       elif [ -f "requirements.txt" ]; then
      #         pip install -r requirements.txt
      #         pytest
      #       else
      #         echo "No test runner found. Skipping test step."
      #       fi
      #     fi

      # - name: Build Docker image
      #   run: |
      #     SERVICE="${{ github.event.inputs.service }}"
      #     if [ "$SERVICE" == "frontend" ]; then
      #       docker build -t ghcr.io/wellpt-org/frontend-service:${{ steps.set-tag.outputs.tag }} ./frontend
      #     else
      #       docker build -t ghcr.io/wellpt-org/$SERVICE-service:${{ steps.set-tag.outputs.tag }} ./backend/$SERVICE
      #     fi

      # - name: Push Docker image
      #   run: |
      #     SERVICE="${{ github.event.inputs.service }}"
      #     if [ "$SERVICE" == "frontend" ]; then
      #       docker push ghcr.io/wellpt-org/frontend-service:${{ steps.set-tag.outputs.tag }}
      #     else
      #       docker push ghcr.io/wellpt-org/$SERVICE-service:${{ steps.set-tag.outputs.tag }}
      #     fi
