name: Triggered CI for Changed Services

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  matrix-dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(github.event.client_payload.services) }}

    steps:
      - name: Dispatch CI workflow for ${{ matrix.service }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: WellPT-Profect-2th/ci
          workflow: ${{ matrix.service }}-build.yml
          inputs: |
            {
              "service": "${{ matrix.service }}",
              "sha": "${{ github.event.client_payload.sha }}"
            }