name: Build and Release

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      sha:
        required: true
        type: string
    secrets:
      DEV_REPO_PAT:
        required: true
      OPS_REPO_PAT:
        required: true
      GHCR_PAT:
        required: true

jobs:  
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          repository: WellPT-Profect-2th/dev
          token: ${{ secrets.DEV_REPO_PAT }}

      - name: Docker build
        run: |
          docker build -t ghcr.io/wellpt-profect-2th/${{ inputs.service }}:${{ inputs.sha }} backend/${{ inputs.service }}
          docker tag ghcr.io/wellpt-profect-2th/${{ inputs.service }}:${{ inputs.sha }} ghcr.io/wellpt-profect-2th/${{ inputs.service }}:latest

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/wellpt-profect-2th/${{ inputs.service }}:${{ inputs.sha }}
          docker push ghcr.io/wellpt-profect-2th/${{ inputs.service }}:latest

  update_tag_in_ops:
    needs: build_and_push
    runs-on: ubuntu-latest 
    steps:
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: update tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.OPS_REPO_PAT }}@github.com/WellPT-Profect-2th/ops.git
          cd ops/${{ inputs.service }}

          yq eval ".images[0].newTag = \"${{ inputs.sha }}\"" -i kustomization.yaml

          git add kustomization.yaml
          git commit -m "ci: update ${{ inputs.service }} image tag to ${{ inputs.sha }}"
          git push