name: Chatbot Test CI

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름'
        required: true
        default: 'chatbot'
      sha:
        description: '빌드할 커밋 SHA'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          repository: WellPT-Profect-2th/dev
          token: ${{ secrets.DEV_REPO_PAT }}

      - name: Set environment variables
        run: |
          {
            echo "REDIS_SERVER=${{ vars.REDIS_SERVER }}"
            echo "REDIS_PORT=${{ vars.REDIS_PORT }}"
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
            echo "PRODUCT_SERVER_ADDR=${{ vars.PRODUCT_SERVER_ADDR }}"
            echo "PRODUCT_SERVER_PORT=${{ vars.PRODUCT_SERVER_PORT }}"
          } | tee -a .env >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd ./backend/${{ inputs.service }}
          pip install -r requirements.txt
          pip install pytest
          
          for d in exception models routers services tests; do
            touch "$d/__init__.py"
          done

          PYTHONPATH=. pytest

  build_and_release:
    needs: test
    uses: ./.github/workflows/build-and-release.yml
    with:
      service: ${{ inputs.service }}
      sha: ${{ inputs.sha }}