name: Frontend CI

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름'
        required: true
        default: 'frontend'
      sha:
        description: '빌드할 커밋 SHA'
        required: true

jobs:
  build_and_release:
    needs: test
    uses: ./.github/workflows/build-and-release.yml
    with:
      service: ${{ inputs.service }}
      sha: ${{ inputs.sha }}
