name: Frontend CI Build

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름'
        required: true
        default: 'frontend'
      sha:
        description: '빌드할 커밋 SHA'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          repository: WellPT-Profect-2th/dev
          token: ${{ secrets.DEV_REPO_PAT }}

      - name: Docker build
        id: set-tag
        run: |
          TAG=${{ inputs.sha }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          docker build -t ghcr.io/wellpt-profect-2th/${{ inputs.service }}:$TAG ${{ inputs.service }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/wellpt-profect-2th/${{ inputs.service }}:${{ steps.set-tag.outputs.tag }}
