name: Gateway CI

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름'
        required: true
        default: 'gateway'
      sha:
        description: '빌드할 커밋 SHA'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          repository: WellPT-Profect-2th/dev
          token: ${{ secrets.DEV_REPO_PAT }}

      - name: Set environment variables
        run: |
          {
            echo "API_GATEWAY_PORT=${{ vars.API_GATEWAY_PORT }}"
            echo "NEXT_SERVER=${{ vars.NEXT_SERVER }}"
            echo "USER_SERVER_ADDR=${{ vars.USER_SERVER_ADDR }}"
            echo "USER_SERVER_PORT=${{ vars.USER_SERVER_PORT }}"
            echo "AD_SERVER_ADDR=${{ vars.AD_SERVER_ADDR }}"
            echo "AD_SERVER_PORT=${{ vars.AD_SERVER_PORT }}"
            echo "PRODUCT_SERVER_ADDR=${{ vars.PRODUCT_SERVER_ADDR }}"
            echo "PRODUCT_SERVER_PORT=${{ vars.PRODUCT_SERVER_PORT }}"
            echo "REVIEW_SERVER_ADDR=${{ vars.REVIEW_SERVER_ADDR }}"
            echo "REVIEW_SERVER_PORT=${{ vars.REVIEW_SERVER_PORT }}"
            echo "CHATBOT_SERVER_ADDR=${{ vars.CHATBOT_SERVER_ADDR }}"
            echo "CHATBOT_SERVER_PORT=${{ vars.CHATBOT_SERVER_PORT }}"
            echo "RECOMMEND_SERVER_ADDR=${{ vars.RECOMMEND_SERVER_ADDR }}"
            echo "RECOMMEND_SERVER_PORT=${{ vars.RECOMMEND_SERVER_PORT }}"
          } | tee -a .env >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd ./backend/${{ inputs.service }}
          ./gradlew test

  build_and_release:
    needs: test
    uses: ./.github/workflows/build-and-release.yml
    with:
      service: ${{ inputs.service }}
      sha: ${{ inputs.sha }}
    secrets:
      DEV_REPO_PAT: ${{ secrets.DEV_REPO_PAT }}
      OPS_REPO_PAT: ${{ secrets.OPS_REPO_PAT }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}