name: Product CI Build

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름'
        required: true
        default: 'product'
      sha:
        description: '빌드할 커밋 SHA'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          repository: WellPT-Profect-2th/dev
          token: ${{ secrets.DEV_REPO_PAT }}

      - name: Set environment variables
        run: |
          {
            echo "PRODUCT_DB_URL=${{ vars.PRODUCT_DB_URL }}"
            echo "PRODUCT_DB_USERNAME=${{ vars.PRODUCT_DB_USERNAME }}"
            echo "PRODUCT_DB_PASSWORD=${{ vars.PRODUCT_DB_PASSWORD }}"
            echo "ELASTICSEARCH_HOST=${{ vars.ELASTICSEARCH_HOST }}"
          } | tee -a .env >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd ./backend/${{ inputs.service }}
          ./gradlew test

  build_and_release:
    needs: test
    uses: ./.github/workflows/build-and-release.yaml
    with:
      service: ${{ inputs.service }}
      sha: ${{ inputs.sha }}