name: Review Test CI

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름'
        required: true
        default: 'review'
      sha:
        description: '빌드할 커밋 SHA'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          repository: WellPT-Profect-2th/dev
          token: ${{ secrets.DEV_REPO_PAT }}

      - name: Set environment variables
        run: |
          {
            echo "REVIEW_DATABASE_URL=${{ vars.REVIEW_DATABASE_URL }}"
            echo "REVIEW_MYSQL_ROOT_PASSWORD=${{ vars.REVIEW_MYSQL_ROOT_PASSWORD }}"
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
            echo "KAFKA_BOOTSTRAP_SERVERS=${{ vars.KAFKA_BOOTSTRAP_SERVERS }}"
          } | tee -a .env >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd ./backend/${{ inputs.service }}
          pip install -r requirements.txt
          pip install pytest

          for d in ai consumer exceptions models routers services tests utils; do
            touch "$d/__init__.py"
          done

          PYTHONPATH=. pytest

  build_and_release:
    needs: test
    uses: ./.github/workflows/build-and-release.yml
    with:
      service: ${{ inputs.service }}
      sha: ${{ inputs.sha }}
    secrets:
      DEV_REPO_PAT: ${{ secrets.DEV_REPO_PAT }}
      OPS_REPO_PAT: ${{ secrets.OPS_REPO_PAT }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}      
