name: Triggered CI for gateway test

jobs:
  matrix-dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 'gateway'

    steps:
      - name: Dispatch CI workflow for gateway
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: WellPT-Profect-2th/ci
          workflow: ${{ matrix.service }}-build.yml
          inputs: |
            {
              "service": "${{ matrix.service }}",
              "sha": "test"
            }