name: Triggered CI for gateway test

on:
  workflow_dispatch:
    inputs:
      service: 'gateway'
      sha: 'test'

jobs:
  matrix-dispatch:
    steps:
      - name: Dispatch CI workflow for gateway
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: WellPT-Profect-2th/ci
          workflow: ${{ inputs.service }}-build.yml
          inputs: |
            {
              "service": "${{ inputs.service }}",
              "sha": "${{ inputs.sha }}"
            }