name: Triggered CI for gateway test

on:
  workflow_dispatch:
    inputs:
      service:
        description: '서비스 이름'
        required: true
        default: 'gateway'
      sha:
        description: '빌드할 커밋 SHA'
        required: true
        default: 'test'

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch CI workflow for gateway
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: WellPT-Profect-2th/ci
          workflow: ${{ inputs.service }}-build.yml
          inputs: |
            {
              "service": "${{ inputs.service }}",
              "sha": "${{ inputs.sha }}"
            }
